### ISSUE TITLE
Unable to use with Emacs < 24.3

### ISSUE THREAD

**Issue by sergeyklay** [flycheck/emacs-travis#10]
From the README.md:

> `$EMACS_VERSION`: The Emacs version to install. Supports any released version of GNU Emacs (tested with 24.1 and upwards), release candidates (e.g. `25.1-rc2`) or the special value `snapshot` to clone the latest `master` from Emacs’ Git. Defaults to the latest stable release of GNU Emacs.

Well, readme says that _"tested with 24.1 and upwards"._ I just tested this by adding in my `.travis.yml` versions as follows:
```diff
env:
  matrix:
+    - EMACS_VERSION=24.1
+    - EMACS_VERSION=24.2
     - EMACS_VERSION=24.3
     - EMACS_VERSION=24.4
     - EMACS_VERSION=24.5
     - EMACS_VERSION=25.1
     - EMACS_VERSION=25.2
     - EMACS_VERSION=snapshot
```

**Output for Emacs 24.1**:
```
$ make -s -f emacs-travis.mk install_emacs
Download Emacs 24.1 from https://ftp.gnu.org/gnu/emacs/emacs-24.1.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314  100   314    0     0    112      0  0:00:02  0:00:02 --:--:--   112
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [download_emacs_stable] Error 2
```

Note: There is no `emacs-24.1.tar.xz` file. See: https://ftp.gnu.org/gnu/emacs/ . Refs: https://github.com/flycheck/emacs-travis/pull/8

**Output for Emacs 24.2**:
```
$ make -s -f emacs-travis.mk install_emacs
Download Emacs 24.2 from https://ftp.gnu.org/gnu/emacs/emacs-24.2.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33.1M  100 33.1M    0     0  7198k      0  0:00:04  0:00:04 --:--:-- 10.3M
Configure Emacs 24.2
configure: WARNING: unrecognized options: --enable-silent-rules, --without-all
configure: WARNING: unrecognized options: --enable-silent-rules, --without-all
...
...
...
/usr/bin/install: cannot stat ‘src/emacs’: No such file or directory
make[1]: *** [install-arch-dep] Error 1
/bin/sh: 1: ../src/emacs: not found
/bin/sh: 1: ../src/emacs: not found
/bin/sh: 1: ../src/emacs: not found
make[2]: *** [quail/CCDOSPY.elc] Error 127
make[2]: *** Waiting for unfinished jobs....
...
...
...
Adding name emacs-24.2.1
make[1]: *** [install-leim] Error 2
make: *** [install_emacs] Error 2
```

**Comment by fmdkdd** [comment]
Indeed.  We could change the README to 24.2 and up.

Is there a point to testing for 24.1?  That release is 5 years old now, and adding logic to grab GZ or XZ or BZ2 for this special case isn't worth it.

**Comment by sergeyklay** [comment]
As you can see there is issue with 24.2 too

**Comment by fmdkdd** [comment]
Oh right.  What's the issue here exactly?  The archive does not have the same hierarchy?

In any case, unless there's an easy fix to make these work, I would move to update the notes to state that we support only Emacs 24.3 and up.
