### ISSUE TITLE
Relationship with EVM

### ISSUE THREAD

**Issue by DamienCassou** [flycheck/emacs-travis#12]
What are the differences between emacs-travis and [evm](https://github.com/rejeep/evm)?

/cc @rejeep

**Comment by rejeep** [comment]
Never seen this before but it looks like it compiles Emacs from scratch each time and Evm provides binaries. Evm is also meant to be used for your local Emacs management.

**Comment by fmdkdd** [comment]
@rejeep is about right.  We compile from source, including the current Emacs master.  And `emacs-travis` is made specifically for use on Travis.
