### ISSUE TITLE
Builds failing on travis

### ISSUE THREAD

**Issue by felipeochoa** [flycheck/emacs-travis#13]
I think something changed in the travis environment, because `make -f emacs-travis.mk install_emacs` now fails with the following error:

> **************************************************
> Warning: Your system has a gap between BSS and the
> heap (2525848 bytes).  This usually means that exec-shield
> or something similar is in effect.  The dump may
> fail because of this.  See the section about
> exec-shield in etc/PROBLEMS for more information.
> **************************************************
> make[2]: *** [bootstrap-emacs] Segmentation fault (core dumped)
> make[1]: *** [src] Error 2
> make: *** [install_emacs] Error 2
> The command "make -f emacs-travis.mk install_emacs" failed and exited with 2 during .

Here are a couple of failed builds:
* https://travis-ci.org/felipeochoa/god-mode/builds/328736149
* https://travis-ci.org/felipeochoa/rjsx-mode/builds/328738972

**Comment by greghendershott** [comment]
I'm seeing the same thing.

- A Travis CI "CRON" build from about a month ago [succeeded](https://travis-ci.org/greghendershott/racket-mode/builds/315926283).

- But suddenly a couple days ago a CRON build of the exact same commit [failed](https://travis-ci.org/greghendershott/racket-mode/builds/328470463).

**Comment by fmdkdd** [comment]
Indeed, I'm seeing failures as well after emptying the cache on our Travis builds.  Compiling Emacs from source now fails.  In fact, I'm getting a core dump trying to compile (24.5) on my machine as well, so it might not be an issue with Travis:
```
/bin/sh: line 7:  8304 Segmentation fault      (core dumped) ./temacs --batch --load loadup bootstrap
```
And the `emacs-travis` script hasn't changed since the succeeded builds, so I don't think it's the issue either.

**Comment by greghendershott** [comment]
Although I don't really know anything about building Emacs, I want to help somehow.

I know how to read blog posts and how to push buttons to see what happens. :smile:  In that spirit:

- I noticed this Travis blog post in December: [New Trusty images are now live!](https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch). OK that sounds suspicious.

- I [tried its recipe to downgrade to the previous image](https://github.com/greghendershott/racket-mode/commit/20c4c1d16adb5463f5a65b13fbd8879d5a0b9c63) and [things seem to work again](https://travis-ci.org/greghendershott/racket-mode/builds/328896271). Yay.

- The Travis blog post asks for people to report issues.

  - I don't see this on their [list of known issues](https://github.com/travis-ci/travis-ci/issues/8870).

  - Should you raise it [here](https://github.com/travis-ci/travis-ci/issues)?  (Although I'm happy to, it would probably carry more weight if you do?)

**Comment by fmdkdd** [comment]
Looks like this is it!  It seems to work fine with the previous Trusty image.  I'll add the workaround to the README until the issue is resolved.

> Should you raise it here?

[Done](https://github.com/travis-ci/travis-ci/issues/9073).  Thank you for finding a workaround 👍

**Comment by felipeochoa** [comment]
@greghendershott Thanks a ton Greg! The change worked for me: https://travis-ci.org/felipeochoa/rjsx-mode/builds/329049924. 

@fmdkdd From my POV, this issue is resolved, and it seems like it's more a travis issue. Feel free to close if you like!

**Comment by fmdkdd** [comment]
@felipeochoa Thanks for reporting.  I'll keep this open until the upstream issue is fixed.  I'm not sure if the workaround can work in the long run (i.e., if Travis drops the previous image completely).

**Comment by greghendershott** [comment]
Yes. Also: Needing to use `sudo: required` to get the older image, means [using a different infrastructure](https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments).

**Comment by fmdkdd** [comment]
Update: the issue seems to be with container-based builds specifically, and not the update from December.  See travis-ci/travis-ci#9061 (and [this comment](https://github.com/travis-ci/travis-ci/issues/9061#issuecomment-3575426690) specifically). 

That means `sudo: required` is necessary for building Emacs, but we can at least use the current image.

An alternative would be to grab binaries instead of building from source.  See [EVM](https://github.com/rejeep/evm) and https://github.com/npostavs/emacs-travis/releases.
