### ISSUE TITLE
emacs-25.1 fails on os x

### ISSUE THREAD

**Issue by ksjogo** [flycheck/emacs-travis#2]
```
[0K$ make -f emacs-travis.mk install_emacs install_cask

Download Emacs 25.1 from https://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.xz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  6 40.5M    6 2832k    0     0  3148k      0  0:00:13 --:--:--  0:00:13 3146k
 24 40.5M   24  9.9M    0     0  5349k      0  0:00:07  0:00:01  0:00:06 5347k
 46 40.5M   46 18.9M    0     0  6661k      0  0:00:06  0:00:02  0:00:04 6659k
 70 40.5M   70 28.6M    0     0  7535k      0  0:00:05  0:00:03  0:00:02 7534k
 97 40.5M   97 39.3M    0     0  8222k      0  0:00:05  0:00:04  0:00:01 8221k
100 40.5M  100 40.5M    0     0  8283k      0  0:00:05  0:00:05 --:--:-- 9408k

Install Emacs 25.1

configure: error: Non-toolkit scroll bars are not implemented for Nextstep.

make: *** [install_emacs] Error 1



travis_time:end:1121f4f8:start=1474373164000000000,finish=1474373189000000000,duration=25000000000
[0K

[31;1mThe command "make -f emacs-travis.mk install_emacs install_cask" failed and exited with 2 during .[0m
```

**Comment by ksjogo** [comment]
Build log with adapted conf flags: https://travis-ci.org/ksjogo/emacs-libgit2/jobs/161355881

**Comment by lunaryorn** [comment]
@ksjogo Thanks for reporting this issue, sorry for my delayed response.

I never tested this on MacOS, so it's no surprise that it doesn't work.  Flycheck doesn't test against MacOS on Travis CI, so as far as I'm concerned I won't try to make it work on MacOS myself.

I'm sorry but you'll need to look at this yourself.  I'm closing as "wontfix".

**Comment by lunaryorn** [comment]
Which is not to say that I wouldn't accept a pull request, so if you can make it build on OS X I'd happily look at a patch :blush:

**Comment by vermiculus** [comment]
I had to add `--with-gameuser=$USER` to the config options and then I had to `ln -s $(HOME)/emacs/$(EMACS_VERSION)/nextstep/Emacs.app/Contents/MacOS/Emacs $(HOME)/bin/emacs` on the macOS builds.

Was able to [get it working](https://travis-ci.org/magit/libegit2/builds/387637928) for magit/libegit2. It took me *way* longer than I'd like to admit.
